### ISSUE TITLE
Exception error at Db.cs

### ISSUE THREAD

**Issue by ghost** [wickyaswal/c-sharp-mysql-database-class#1]
hi, ive encountered an error while running the application at Db.cs line 30, encountered it while running the example program, included in the source code. i'm into it, but i cant understand it yet, just to let you know sir.i think its having an issue about the db.bind method of parsing bindings, i'm using Visual Studio ultimate 2012.

**Comment by wickyaswal** [comment]
Have you executed the SQL dump on your MySQL server ?

**Comment by ghost** [comment]
yup done that, the problem i think lies in the bind methods, which replaces @values with another value and it seems not working on me i thinks its in this line
  db.bind("id", "1");
  string[] sperson = db.row("SELECT \* FROM persons WHERE id = @id");
which based on my debugging session the "@id" is not replaced by 1, producing exception in the process.

**Comment by wickyaswal** [comment]
Thanks Pedro ! 
It's fixed now. 

Just copy the code from DB.cs.

If you are curios about the solution, check the commit description.

Thanks agian.
